import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Pića i hrana",
    nameEn: "Drinks & Food",
    slug: "pica-i-hrana",
    icon: "🍽️",
    subcategories: [
      { id: "1-1", name: "Pivo", nameEn: "Beer", slug: "pivo", categoryId: "1" },
      { id: "1-2", name: "Vina", nameEn: "Wines", slug: "vina", categoryId: "1" },
      { id: "1-3", name: "Alkoholna pića", nameEn: "Alcoholic Drinks", slug: "alkoholna-pica", categoryId: "1" },
      { id: "1-4", name: "Sokovi", nameEn: "Juices", slug: "sokovi", categoryId: "1" },
      { id: "1-5", name: "Slatkiši", nameEn: "Sweets", slug: "slatkisi", categoryId: "1" },
      { id: "1-6", name: "Voda", nameEn: "Water", slug: "voda", categoryId: "1" },
      { id: "1-7", name: "Grickalice", nameEn: "Snacks", slug: "grickalice", categoryId: "1" },
      { id: "1-8", name: "Energetska pića", nameEn: "Energy Drinks", slug: "energetska-pica", categoryId: "1" },
      { id: "1-9", name: "Čajevi", nameEn: "Teas", slug: "cajevi", categoryId: "1" },
      { id: "1-10", name: "Mleko", nameEn: "Milk", slug: "mleko", categoryId: "1" },
      {
        id: "1-11",
        name: "Kafa i dodaci za kafu",
        nameEn: "Coffee & Coffee Accessories",
        slug: "kafa-dodaci",
        categoryId: "1",
      },
      { id: "1-12", name: "Med", nameEn: "Honey", slug: "med", categoryId: "1" },
    ],
  },
  {
    id: "2",
    name: "Hemija",
    nameEn: "Household",
    slug: "hemija",
    icon: "🧼",
    subcategories: [
      { id: "2-1", name: "Toalet papir", nameEn: "Toilet Paper", slug: "toalet-papir", categoryId: "2" },
      { id: "2-2", name: "Rukavice zaštitne", nameEn: "Protective Gloves", slug: "rukavice-zastitne", categoryId: "2" },
      {
        id: "2-3",
        name: "Održavanje kuhinje",
        nameEn: "Kitchen Maintenance",
        slug: "odrzavanje-kuhinje",
        categoryId: "2",
      },
      { id: "2-4", name: "Čišćenje stakla", nameEn: "Glass Cleaning", slug: "ciscenje-stakla", categoryId: "2" },
      {
        id: "2-5",
        name: "Sredstvo za čišćenje poda",
        nameEn: "Floor Cleaning Products",
        slug: "ciscenje-poda",
        categoryId: "2",
      },
      { id: "2-6", name: "Osveživač prostora", nameEn: "Air Freshener", slug: "osvezivac-prostora", categoryId: "2" },
      {
        id: "2-7",
        name: "Kese i kante za smeće",
        nameEn: "Trash Bags & Bins",
        slug: "kese-kante-smece",
        categoryId: "2",
      },
      { id: "2-8", name: "Dispanzeri držači", nameEn: "Dispenser Holders", slug: "dispanzeri-drzaci", categoryId: "2" },
    ],
  },
  {
    id: "3",
    name: "Kancelarijski materijal",
    nameEn: "Office Supplies",
    slug: "kancelarijski-materijal",
    icon: "📎",
    subcategories: [
      { id: "3-1", name: "Papir", nameEn: "Paper", slug: "papir", categoryId: "3" },
      { id: "3-2", name: "Olovke i hemijske", nameEn: "Pens & Pencils", slug: "olovke-hemijske", categoryId: "3" },
      {
        id: "3-3",
        name: "Fascikle i registratori",
        nameEn: "Folders & Binders",
        slug: "fascikle-registratori",
        categoryId: "3",
      },
    ],
  },
  {
    id: "4",
    name: "Dodatna oprema",
    nameEn: "Additional Equipment",
    slug: "dodatna-oprema",
    icon: "🔧",
    subcategories: [
      { id: "4-1", name: "Alati", nameEn: "Tools", slug: "alati", categoryId: "4" },
      { id: "4-2", name: "Baterije", nameEn: "Batteries", slug: "baterije", categoryId: "4" },
    ],
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Jelen 0.5l limenka",
    nameEn: "Jelen Beer 0.5l can",
    description: "Domaće pivo u limenci",
    descriptionEn: "Domestic beer in can",
    price: 85,
    image: "/beer-can-on-white-background-product-photography.jpg",
    categoryId: "1",
    subcategoryId: "1-1",
    unit: "0.5L",
    unitEn: "0.5L",
    inStock: true,
  },
  {
    id: "2",
    name: "Zaječarsko pivo 0.5l",
    nameEn: "Zaječarsko Beer 0.5l",
    description: "Svetlo pivo",
    descriptionEn: "Light beer",
    price: 90,
    image: "/beer-bottle-on-white-background-product-photograph.jpg",
    categoryId: "1",
    subcategoryId: "1-1",
    unit: "0.5L",
    unitEn: "0.5L",
    inStock: true,
    discount: 10,
  },
  {
    id: "3",
    name: "Vranac crno vino",
    nameEn: "Vranac Red Wine",
    description: "Crno vino iz Crne Gore",
    descriptionEn: "Red wine from Montenegro",
    price: 650,
    image: "/red-wine-bottle-on-white-background-product-photog.jpg",
    categoryId: "1",
    subcategoryId: "1-2",
    unit: "0.75L",
    unitEn: "0.75L",
    inStock: true,
  },
  {
    id: "4",
    name: "Coca Cola 1.5L",
    nameEn: "Coca Cola 1.5L",
    description: "Gazirano piće",
    descriptionEn: "Carbonated soft drink",
    price: 129,
    image: "/cola-bottle-on-white-background-product-photograph.jpg",
    categoryId: "1",
    subcategoryId: "1-4",
    unit: "1.5L",
    unitEn: "1.5L",
    inStock: true,
  },
  {
    id: "5",
    name: "Knjaz Miloš mineralna voda",
    nameEn: "Knjaz Miloš Mineral Water",
    description: "Prirodna mineralna voda",
    descriptionEn: "Natural mineral water",
    price: 69,
    image: "/mineral-water-bottle-on-white-background-product-p.jpg",
    categoryId: "1",
    subcategoryId: "1-6",
    unit: "1.5L",
    unitEn: "1.5L",
    inStock: true,
  },
  {
    id: "6",
    name: "Red Bull 250ml",
    nameEn: "Red Bull 250ml",
    description: "Energetsko piće",
    descriptionEn: "Energy drink",
    price: 180,
    image: "/energy-drink-can-on-white-background-product-photo.jpg",
    categoryId: "1",
    subcategoryId: "1-8",
    unit: "250ml",
    unitEn: "250ml",
    inStock: true,
  },
  {
    id: "7",
    name: "Milka čokolada 100g",
    nameEn: "Milka Chocolate 100g",
    description: "Mlečna čokolada",
    descriptionEn: "Milk chocolate",
    price: 199,
    image: "/chocolate-bar-on-white-background-product-photogra.jpg",
    categoryId: "1",
    subcategoryId: "1-5",
    unit: "100g",
    unitEn: "100g",
    inStock: true,
    discount: 15,
  },
  {
    id: "8",
    name: "Grand Kafa 200g",
    nameEn: "Grand Coffee 200g",
    description: "Mlevena kafa",
    descriptionEn: "Ground coffee",
    price: 449,
    image: "/coffee-package-on-white-background-product-photogr.jpg",
    categoryId: "1",
    subcategoryId: "1-11",
    unit: "200g",
    unitEn: "200g",
    inStock: true,
  },
  {
    id: "9",
    name: "Toalet papir 3-slojni 10/1",
    nameEn: "Toilet Paper 3-ply 10/1",
    description: "Meki toalet papir",
    descriptionEn: "Soft toilet paper",
    price: 350,
    image: "/toilet-paper-rolls-on-white-background-product-pho.jpg",
    categoryId: "2",
    subcategoryId: "2-1",
    unit: "10 rolni",
    unitEn: "10 rolls",
    inStock: true,
  },
  {
    id: "10",
    name: "Domestos WC gel 750ml",
    nameEn: "Domestos WC Gel 750ml",
    description: "Sredstvo za čišćenje WC šolje",
    descriptionEn: "Toilet bowl cleaner",
    price: 280,
    image: "/cleaning-bottle-on-white-background-product-photog.jpg",
    categoryId: "2",
    subcategoryId: "2-3",
    unit: "750ml",
    unitEn: "750ml",
    inStock: true,
  },
  {
    id: "11",
    name: "Kese za smeće 60L 20/1",
    nameEn: "Trash Bags 60L 20/1",
    description: "Crne kese za smeće",
    descriptionEn: "Black trash bags",
    price: 220,
    image: "/trash-bags-package-on-white-background-product-pho.jpg",
    categoryId: "2",
    subcategoryId: "2-7",
    unit: "20 kom",
    unitEn: "20 pcs",
    inStock: true,
  },
  {
    id: "12",
    name: "A4 papir 500 listova",
    nameEn: "A4 Paper 500 sheets",
    description: "Beli papir za štampanje",
    descriptionEn: "White printing paper",
    price: 550,
    image: "/paper-stack-on-white-background-product-photograph.jpg",
    categoryId: "3",
    subcategoryId: "3-1",
    unit: "500 listova",
    unitEn: "500 sheets",
    inStock: true,
  },
  {
    id: "13",
    name: "Hemijska olovka plava",
    nameEn: "Blue Ballpoint Pen",
    description: "Standardna hemijska olovka",
    descriptionEn: "Standard ballpoint pen",
    price: 35,
    image: "/blue-pen-on-white-background-product-photography.jpg",
    categoryId: "3",
    subcategoryId: "3-2",
    unit: "1 kom",
    unitEn: "1 pc",
    inStock: true,
  },
  {
    id: "14",
    name: "Baterije AA 4/1",
    nameEn: "AA Batteries 4/1",
    description: "Alkalne baterije",
    descriptionEn: "Alkaline batteries",
    price: 320,
    image: "/batteries-pack-on-white-background-product-photogr.jpg",
    categoryId: "4",
    subcategoryId: "4-2",
    unit: "4 kom",
    unitEn: "4 pcs",
    inStock: true,
  },
  {
    id: "15",
    name: "Fanta Narandža 2L",
    nameEn: "Fanta Orange 2L",
    description: "Gazirano piće sa ukusom narandže",
    descriptionEn: "Carbonated orange drink",
    price: 139,
    image: "/orange-soda-bottle-on-white-background-product-pho.jpg",
    categoryId: "1",
    subcategoryId: "1-4",
    unit: "2L",
    unitEn: "2L",
    inStock: true,
    discount: 20,
  },
  {
    id: "16",
    name: "Čips Lays 150g",
    nameEn: "Lays Chips 150g",
    description: "Hrskavi čips",
    descriptionEn: "Crispy chips",
    price: 189,
    image: "/placeholder.svg?height=400&width=400",
    categoryId: "1",
    subcategoryId: "1-7",
    unit: "150g",
    unitEn: "150g",
    inStock: true,
  },
]
